# Generated by Django 5.1 on 2024-09-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_temp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperture_data',
            name='temperture',
            field=models.FloatField(),
        ),
    ]
