# Generated by Django 5.1 on 2024-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_temp', '0002_alter_temperture_data_temperture'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperture_data',
            name='arm',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
